import shutil
# 24.04.20
configfile: "/home/projects/ku-cbd/people/nurher/holoflow/testing/base/config.yaml"
##
# Assembly
##
rule assembly:
    input:
        read1="{projectpath}/04-MappedToHuman/{sample}_1.fastq",
        read2="{projectpath}/04-MappedToHuman/{sample}_2.fastq"

    output:
        "{projectpath}/05-Assembly/{sample}_assembly/empty_file_to_remove"

    params:
        memory=expand("{memory}", memory=config['memory']),
        klist_megahit=expand("{klist_megahit}", klist_megahit=config['klist_megahit']),
        klist_spades=expand("{klist_spades}", klist_spades=config['klist_spades']),
        threads=expand("{threads}", threads=config['threads']),
        assembler=expand("{assembler}", assembler=config['assembler']),
        out_dir="{projectpath}/05-Assembly/{sample}_assembly",
        temp_assembly="{projectpath}/05-Assembly/{sample}_assembly/temp_assembly.fa"

    shell:
        """
        python b/holo-assembly.py -1 {input.read1} -2 {input.read2} -m {params.memory} -k_megahit {params.klist_megahit} -k_spades {params.klist_spades} -a {params.assembler} -empty_o {output} -temp_a {params.temp_assembly}
        """




rule assembly_reformat:
    input:
        "{projectpath}/04-MappedToHuman/{sample}.stats"
    output:
        "{projectpath}/05-Assembly/{sample}.stats"
    params:
        in_assembly="{projectpath}/05-Assembly/{sample}_assembly/temp_assembly.fa",
        out_assembly="{projectpath}/05-Assembly/{sample}.fa"

    shell:
        """
        python b/holo-assembly_reformat.py -in_a {params.in_assembly} -out_a {params.out_assembly} -st_in {input} -st_out {output}
        """
