configfile: "config.yaml"

rule qual_filt:
    input:
      read1="{projectpath}/00-Rawdata/{sample}_1.fastq.gz",
      read2="{projectpath}/00-Rawdata/{sample}_2.fastq.gz"
    output:
      read1="{projectpath}/01-QualityFiltered/{sample}_1.fastq",
      read2="{projectpath}/01-QualityFiltered/{sample}_2.fastq"
    params:
        maxns = "5",
        minquality = "30",
        threads = "24"
    shell:
        "module unload gcc tools ngs && module load tools gcc/5.4.0 AdapterRemoval/2.1.3 && AdapterRemoval --file1 {input.read1} --file2 {input.read2} --output1 {output.read1} --output2 {output.read2} --trimqualities --trimns --maxns {params.maxns} --minquality {params.minquality} --threads {params.threads}"

##
# Duplicate removal (single-based)
##

rule dup_rem_single:
    input:
      read1="{projectpath}/01-QualityFiltered/{sample}_1.fastq",
      read2="{projectpath}/01-QualityFiltered/{sample}_2.fastq"
    output:
      read1="{projectpath}/02-DuplicatesRemoved/{sample}_1.fastq.tmp",
      read2="{projectpath}/02-DuplicatesRemoved/{sample}_2.fastq.tmp"
    run:
      shell("module load tools pigz/2.3.4 seqkit/0.7.1 && cat {input.read1} | seqkit rmdup -s -o {output.read1}")
      shell("module load tools pigz/2.3.4 seqkit/0.7.1 && cat {input.read2} | seqkit rmdup -s -o {output.read2}")

rule dup_rem_single_repair:
    input:
      read1="{projectpath}/02-DuplicatesRemoved/{sample}_1.fastq.tmp",
      read2="{projectpath}/02-DuplicatesRemoved/{sample}_2.fastq.tmp"
    output:
      read1="{projectpath}/02-DuplicatesRemoved/{sample}_1.fastq",
      read2="{projectpath}/02-DuplicatesRemoved/{sample}_2.fastq"
    shell:
      "module load tools jre/1.8.0 bbmap/36.49 && repair.sh in={input.read1} in2={input.read2} out={output.read1} out2={output.read2} overwrite=t && rm {input.read1} {input.read2}"

##
# Duplicate removal (pair-based)
##

rule dup_rem_paired:
    input:
      read1="{projectpath}/01-QualityFiltered/{sample}_1.fastq",
      read2="{projectpath}/01-QualityFiltered/{sample}_2.fastq"
    output:
      "{projectpath}/02-DuplicatesRemoved/{sample}.merged.fastq"
    run:
      shell("module load tools pigz/2.3.4 seqkit/0.7.1 && paste -d '_' {input.read1} {input.read2} | seqkit rmdup -s -j 28 -o {output} ")

rule dup_rem_paired_repair:
    input:
      "{projectpath}/02-DuplicatesRemoved/{sample}.merged.fastq"
    output:
      read1="{projectpath}/02-DuplicatesRemoved/{sample}_1.fastq",
      read2="{projectpath}/02-DuplicatesRemoved/{sample}_2.fastq"
    run:
      shell("cut --delimiter='_' -f1 {input} > {output.read1}")
      shell("cut --delimiter='_' -f2 {input} > {output.read2}")
      shell("rm {input}")
