
# WOKRKFLOW 1 - Functional annotation on coassembly directly
# Run DRAM
# Ask Bent petersen to download dbs for us

#28.04.21

rule get_paths:
   input:
       holopath=expand("{holopath}", holopath=config['holopath']),
       logpath=expand("{logpath}", logpath=config['logpath'])


################################################################################################################
####################################      Annotation of assembly file     ######################################
################################################################################################################

##
# Assembly
##
rule assembly:
   input:
       read1="{projectpath}/MAB_00-InputData/{group}.fastq",
   output:
       directory"{projectpath}/MAB_01-Annotation/{group}"
   params:
       threads=expand("{threads}", threads=config['threads']),
       group="{group}"

   shell:
       """
       python {rules.get_paths.input.holopath}/bin/holo-assembly_annotation.py -a {input} -out_dir {output} -ID {params.group} -log {rules.get_paths.input.logpath}
       """
