# dereplication pipeline options
threads:
  40
memory:
  180
#Note, this can impact the depreplication analysis:
#see https://drep.readthedocs.io/en/latest/choosing_parameters.html
mincomp:
  70
#Note, this is quite an important parameter to consider, and will depend on your-
#read length and type of downstream analysis. For more information, see:
#https://instrain.readthedocs.io/en/latest/important_concepts.html
ani:
  98

#SSPACE:
  #True

# phylogeny options

  # low , for species- and strain-level phylogenies
  # medium, for genus- and family-level phylogenies
  # high, for tree-of-life and higher-ranked taxonomic levels phylogenies
# {low,medium,high}
# diversity:
#   low
#
# phylo_db:
#   phylophlan
#
# # {tree, concatenation}
# pipeline:
#   tree
